/*
async(req,res)=> {
try {
    const tasks = await Task.find()
    res.json(tasks)
}catch (error) {
    console.log (eror)
}

})*/

